python -m mepol.src.experiments.goal_rl.py \
    --env "AirHockeyAcc" \
    --env_name "3dof-hit" \
    --num_workers 5 \
    --num_epochs 1000 \
    --batch_size 5000 \
    --traj_len 400 \
    --gamma 0.999 \
    --lambd 0.98 \
    --optimizer "adam" \
    --critic_lr 0.01 \
    --critic_reg 0.001 \
    --critic_iters 5 \
    --critic_batch_size 64 \
    --cg_iters 20 \
    --cg_damping 0.1 \
    --kl_thresh 0.01 \
    --task_space 1 \
    --task_space_vel 0 \
    --use_delta_pos 1 \
    --delta_dim 1 \
    --use_puck_distance 1 \
    --use_tanh 1 \
    --log_std -0.5 \
    --policy_init "/data/air_hockey/thomas/policies/50_max_acceleration-policy"
