alg: ppo
policy: MlpPolicy
lr: 3e-4
steps_per_update: 256
batch_size: 256
n_epochs: 20
gamma: 0.997
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.001
vf_coef: 0.5
max_grad_norm: 0.5
sde_sample_freq: -1
stats_window_size: 100
tensorboard_log: "./"
verbose: 1