hydra.output_subdir: null
learn:
  total_timesteps: 5000000
seed: 204552
log_dir: '/home/airhockey/thomas/data/'
log_interval: 10 # log statistics every n episodes
parallel: 20
label: sde_alpha100
defaults:
  - callbacks:
      - custom_eval
      - checkpoint
      - info_log
  - algorithm:
      sac

