hydra.output_subdir: null
learn:
  total_timesteps: 10000000
seed: null
log_dir: '/tmp/test'
log_interval: 10 # log statistics every n episodes
parallel: 1
label: hit
defaults:
  - callbacks:
      - custom_eval
      - checkpoint
      - info_log
  - algorithm:
      sac

