hydra.output_subdir: null
learn:
  total_timesteps: 5000000
seed: null
log_dir: '/home/airhockey/thomas/data/'
log_interval: 10 # log statistics every n episodes
parallel: 20
label: clip_acceleration_aim_6dof
defaults:
  - callbacks:
      - custom_eval
      - checkpoint
      - info_log
  - algorithm:
      sac

