hydra.output_subdir: null
learn:
  total_timesteps: 35000000
seed: null
log_dir: '/home/airhockey/thomas/data/'
log_interval: 10 # log statistics every n episodes
parallel: 20
label: fineTunedClip_6dof
defaults:
  - callbacks:
      - custom_eval
      - checkpoint
      - info_log
  - algorithm:
      sac

