lr: [1e-1]
initial_rho: hp
ite: 1000
batch_size: 30
episodes_per_theta: 1
env: None
policy: None
data_processor: None
directory: "/Users/ale/results/pgpe"
verbose: False
natural: False
checkpoint_freq: 100
lr_strategy: "adam"
learn_std: False
std_decay: 0
std_min: 1e-5
n_jobs_param: 6
n_jobs_traj: 1